FROM jakubboucek/lamp-devstack-php:5.4-legacy-fixed

LABEL org.label-schema.name="PHP 5.4 (Apache module + Xdebug)"

# Configure Xdebug
COPY legacy/xdebug-2.ini /usr/local/etc/php/conf.d/xdebug.ini

# Prevent interactive block
ARG DEBIAN_FRONTEND=noninteractive

# Install Xdebug
RUN set -eux; \
    pecl install xdebug-2.4.1; \
    pecl clear-cache; \
    docker-php-ext-enable xdebug; \
    rm -rf /var/tmp/* /tmp/*;
