FROM jakubboucek/lamp-devstack-php:8.3

LABEL org.label-schema.name="PHP 8.3 (Apache module + Xdebug)"

# Configure Xdebug
COPY xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini

# Setup PIE working directory
ARG PIE_WORKING_DIRECTORY=/tmp/.pie

# Prevent interactive block
ARG DEBIAN_FRONTEND=noninteractive

# Install Xdebug
RUN set -eux; \
    pie install xdebug/xdebug; \
    rm -rf /var/tmp/* /tmp/*;
