FROM jakubboucek/lamp-devstack-php:7.4

# Configure Xdebug
COPY xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini

# Prevent interactive block
ARG DEBIAN_FRONTEND=noninteractive

# Install Xdebug
RUN set -eux; \
    pecl install xdebug; \
    docker-php-ext-enable xdebug; \
    rm -rf /var/tmp/* /tmp/*;
