FROM php:8.0-cli

LABEL maintainer="Jakub Bouček <pan@jakubboucek.cz>"

# Workdir during installation
WORKDIR /tmp

# OS binaries install && update critical binaries
RUN set -eux; \
    DEBIAN_FRONTEND=noninteractive; \
    apt-get update; \
    apt-get install --no-install-recommends -y \
        ca-certificates \
        libfreetype6-dev \
        libicu-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
        libwebp-dev \
        libxslt-dev \
        libzip-dev \
        openssl \
        unzip \
        zip; \
    docker-php-ext-configure \
        gd --with-freetype --with-jpeg --with-webp; \
    docker-php-ext-install -j$(nproc) \
        mysqli \
        bcmath \
        gd \
        intl \
        pdo_mysql \
        sockets \
        xsl \
        zip; \
    apt-get autoremove -y; \
    apt-get clean; \
    rm -rf /var/lib/apt/lists/* /var/tmp/* /tmp/*;

# Setup Devstack (install Composer)
RUN set -eux; \
    DEBIAN_FRONTEND=noninteractive; \
    curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php; \
    php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer; \
    COMPOSER_BIN_DIR=$(composer global config bin-dir --absolute) 2>/dev/null; \
    echo "export PATH=${COMPOSER_BIN_DIR}:\${PATH}" >> ~/.bashrc; \
    rm -rf /tmp/*;

# Workdir after installation
WORKDIR /
