FROM jakubboucek/lamp-devstack-php:8.1

LABEL org.label-schema.name="PHP 8.1 (Apache module + Xdebug)"

# Configure Xdebug
COPY xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini

# Prevent interactive block
ARG DEBIAN_FRONTEND=noninteractive

# Install Xdebug
RUN set -eux; \
    pecl install xdebug; \
    pecl clear-cache; \
    docker-php-ext-enable xdebug; \
    rm -rf /var/tmp/* /tmp/*;
