FROM php:8.1-cli-buster

LABEL maintainer="Jakub Bouček <pan@jakubboucek.cz>"

# Workdir during installation
WORKDIR /tmp

# Use local mirrors to install Debian updates
COPY sources.list-buster /etc/apt/sources.list

# OS binaries install && update critical binaries
RUN set -eux; \
    DEBIAN_FRONTEND=noninteractive; \
    apt-get update; \
    apt-get install --no-install-recommends -y \
        ca-certificates \
        libc-client-dev \
        libfreetype6-dev \
        libicu-dev \
        libjpeg62-turbo-dev \
        libkrb5-dev \
        libpng-dev \
        libwebp-dev \
        libxslt-dev \
        libzip-dev \
        nano \
        openssl \
        unzip \
        zip; \
    docker-php-ext-configure \
        gd --with-freetype --with-jpeg --with-webp; \
    docker-php-ext-configure \
        imap --with-kerberos --with-imap-ssl; \
    docker-php-ext-install -j$(nproc) \
        bcmath \
        exif \
        gd \
        imap \
        intl \
        mysqli \
        opcache \
        pcntl \
        pdo_mysql \
        sockets \
        xsl \
        zip; \
    apt-get autoremove -y; \
    apt-get clean; \
    rm -rf /var/lib/apt/lists/* /var/tmp/* /tmp/*;

# Configure Apache & PHP
ENV PHP_MAX_EXECUTION_TIME 30
ENV PHP_MEMORY_LIMIT 2G
COPY core.ini /usr/local/etc/php/conf.d/core.ini

# Configure OPcache
ENV PHP_OPCACHE_ENABLE 1
ENV PHP_OPCACHE_ENABLE_CLI 0
ENV PHP_OPCACHE_MEMORY_CONSUPTION 128
ENV PHP_OPCACHE_REVALIDATE_FREQ 2
ENV PHP_OPCACHE_VALIDATE_TIMESTAMPS 1
COPY opcache.ini /usr/local/etc/php/conf.d/opcache.ini

# Setup Devstack (install Composer)
RUN set -eux; \
    DEBIAN_FRONTEND=noninteractive; \
    curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php; \
    php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer; \
    COMPOSER_BIN_DIR=$(composer global config bin-dir --absolute) 2>/dev/null; \
    echo "export PATH=${COMPOSER_BIN_DIR}:\${PATH}" >> ~/.bashrc; \
    rm -rf /tmp/*;

# Workdir after installation
WORKDIR /
