FROM php:7.3-apache

LABEL maintainer="Jakub Bouček <pan@jakubboucek.cz>"

# Workdir during installation
WORKDIR /tmp

# OS binaries install && update critical binaries
RUN set -eux; \
    DEBIAN_FRONTEND=noninteractive; \
    apt-get update; \
    apt-get install --no-install-recommends -y \
        ca-certificates \
        libfreetype6-dev \
        libicu-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
        libwebp-dev \
        libxslt-dev \
        libzip-dev \
        openssl \
        unzip \
        zip; \
    docker-php-ext-configure \
        gd --with-freetype-dir --with-jpeg-dir=/usr/include/ --with-webp-dir=/usr/include/; \
    docker-php-ext-install -j$(nproc) \
        mysqli \
        bcmath \
        gd \
        intl \
        pcntl \
        pdo_mysql \
        sockets \
        xsl \
        zip; \
    a2enmod \
        expires \
        headers \
        rewrite; \
    apt-get autoremove -y; \
    apt-get clean; \
    rm -rf /var/lib/apt/lists/* /var/tmp/* /tmp/*;

# Configure Apache & PHP
COPY php.ini /usr/local/etc/php/conf.d/dev-memory-increase.ini

# Move Apache Document root to sub-directory `www` (PHP frameworks convention)
ENV APACHE_DOCUMENT_ROOT /var/www/html/www

# Setup Devstack (install Composer, setup DocumentRoot)
RUN set -eux \
    DEBIAN_FRONTEND=noninteractive; \
    curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php; \
    php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer; \
    COMPOSER_BIN_DIR=$(composer global config bin-dir --absolute) 2>/dev/null; \
    echo "export PATH=${COMPOSER_BIN_DIR}:\${PATH}" >> ~/.bashrc; \
    sed -ri -e "s!/var/www/html!${APACHE_DOCUMENT_ROOT}!g" /etc/apache2/sites-available/*.conf; \
    rm -rf /tmp/*;

# Workdir after installation
WORKDIR /var/www/html
