FROM jakubboucek/lamp-devstack-php:8.0

# Workdir during installation
WORKDIR /tmp

RUN pecl install xdebug \
    && docker-php-ext-enable xdebug \
    && echo "xdebug.mode=debug" > /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.xdebug.output_dir = \"/var/www/html/temp\"" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && rm -rf /var/tmp/* /tmp/* /tmp/pear/temp/* \
    && php -v

# Workdir after installation
WORKDIR /var/www/html
